name: Extension Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
    - name: Clear npm cache
      run: npm cache clean --force
    - name: Install dependencies
      run: npm ci
    - name: Install Chrome for Puppeteer
      run: npx puppeteer browsers install chrome
    - run: npm run build:dev
    - name: Run tests
      env:
        CI: 'true'
      run: npm test